routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes(['register' => false]);

Route::middleware("auth")
    ->prefix("admin")
    ->as("admin.")
    ->group( function () {

        Route::get("/",  [App\Http\Controllers\Admin\IndexController::class,'index'])->name("index");

        Route::resource('companies', \App\Http\Controllers\Admin\CompanyController::class);
        Route::resource('employees', \App\Http\Controllers\Admin\EmployeeController::class);

    });

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Company extends Model
{
    use HasFactory;

    protected $table = "companies";

    protected $fillable = [
        'name','email', 'logo', 'website'
    ];

    public function employees():HasMany{
        return $this->hasMany(Employee::class);
    }

}

app/Http/Controllers/Admin/CompanyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreCompanyRequest;
use App\Http\Requests\UpdateCompanyRequest;
use App\Models\Company;
use Illuminate\Http\Request;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return view("admin.company.list");

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $data['accion'] = "create";
        $data['title']  = "Crear Compañia";
        $data['btn_action'] = "Guardar";

        return view("admin.company.form",compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCompanyRequest $request)
    {
        //

        $form = $request->validated();

        $company = Company::create($form);

        if($request->file('logo')){

            $image_name = "company_$company->id.".$request->logo->extension();
            $request->logo->move(storage_path('app/public/logos'), $image_name);
            $company->update(['logo'=>"logos/$image_name"]);

        }

        return redirect('admin/companies');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $entry = Company::findOrFail($id);

        $data['accion'] = "show";
        $data['title']  = "Ver Compañia";



        return view("admin.company.show", compact('entry','data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $entry = Company::findOrFail($id);

        $data['accion'] = "edit";
        $data['title']  = "Editar Compañia";
        $data['btn_action'] = "Actualizar";


        return view("admin.company.form", compact('entry','data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCompanyRequest $request, $id)
    {
        //

        //dd($request->all());

        $company = Company::findOrFail($id);

        $form = $request->validated();

        if($request->file('logo')){

            $image_name = "company_$id.".$request->logo->extension();
            $request->logo->move(storage_path('app/public/logos'), $image_name);
            $form['logo'] = "logos/$image_name";

        }

        $company->update($form);

        //dd($company);

        return redirect('admin/companies');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Livewire/Company/BtnDelete.php
<?php

namespace App\Http\Livewire\Company;


use App\Models\Company;
use App\Models\Employee;
use Livewire\Component;

class BtnDelete extends Component
{
    public $company_id;
    public $company;

    protected $listeners =[
        'deleteCompany'
    ];

    public function mount($company){
        $this->company = $company;
        $this->company_id = $company->id;
    }

    public function deleteConfirm($company_id){

        $full_name =$this->company->name;

        $this->dispatchBrowserEvent('SwalConfirm',[
            'title' => 'Eliminar Compañia',
            'html'  => "¿Desea eliminar la Compañia <strong>$full_name ?</strong>",
            'id'    => $company_id
        ]);


    }

    public function deleteCompany($id){

        $empleados = Employee::where("company_id",$id)->get();
        if(isset($empleados)){
            foreach ($empleados as $e){
                $e->delete();
            }
        }

        $company    = Company::find($id);
        if($company){
            $company->delete();
            $this->dispatchBrowserEvent('deletedCompany');
        }

    }


    public function render()
    {
        return view('livewire.company.btn-delete');
    }
}

app/Http/Livewire/CompanyTable.php
<?php

namespace App\Http\Livewire;

use Carbon\Carbon;
use Illuminate\Support\Str;
use Rappasoft\LaravelLivewireTables\DataTableComponent;
use Rappasoft\LaravelLivewireTables\Views\Column;
use App\Models\Company;
use Rappasoft\LaravelLivewireTables\Views\Columns\ImageColumn;


class CompanyTable extends DataTableComponent
{
    protected $model = Company::class;

    public function configure(): void
    {
        $this->setPrimaryKey('id');
    }

    protected $listeners =[
        'refreshList'
    ];

    public function refreshList(){
        //$this->render();
    }

    public function columns(): array
    {
        return [
            Column::make("Id", "id")
                ->sortable(),

            Column::make(__("Nombre"), "name")
                ->sortable()
                ->searchable(),

            Column::make(__("Email"), "email")
                ->sortable()
                ->searchable(),

            Column::make(__("Website"), "website")
                ->sortable()
                ->searchable()
                ->format(
                    fn($value, $row, Column $column) => Str::limit($row->website,30)
                ),
            Column::make(__("Fecha creacion"), "created_at")
                ->sortable()
                ->format(
                    fn($value, $row, Column $column) => Carbon::create($row->created_at)->format("d/m/Y H:i")
                ),
            Column::make(__("Fecha actualización"), "updated_at")
                ->sortable()
                ->format(
                    fn($value, $row, Column $column) => Carbon::create($row->updated_at)->format("d/m/Y H:i")
                ),

            Column::make('Actions','id')
                ->view('admin.company.actions')
                ->html()->excludeFromColumnSelect(),

        ];
    }
}

resources/views/admin/company/actions.blade.php
<div class="btn-group" role="group" aria-label="Acciones">

    <a href="{{ route("admin.companies.show",$row) }}" class="btn btn-sm btn-default">
        <i class="fas fa-fw fa-eye"></i>
    </a>

    <a href="{{ route("admin.companies.edit",$row) }}" class="btn btn-sm btn-primary">
        <i class="fas fa-fw fa-edit"></i>
    </a>

    @livewire("company.btn-delete",['company' => $row])

</div>

resources/views/admin/company/form.blade.php
@extends('adminlte::page')

@section('title',$data['title'])

@section('content_header')
    <h1>{{$data['title']}}</h1>
@stop

@section('content')

    @if(isset($entry))
        <form method="POST"  action="{{ url("admin/companies/".$entry->id) }}" enctype="multipart/form-data" >
        @method('PUT')
    @else
        <form method="POST" action="{{ url("admin/companies") }}" enctype="multipart/form-data" >
    @endif

        @csrf

        <input type="hidden" id="id" name="id" value="{{ isset($entry)?$entry->id:0 }}" />


        <div class="card card-success">
            <div class="card-header">
                <h3 class="card-title">Detalle</h3>
            </div>
            <div class="card-body">

                <div class="form-group">
                    <label for="name">Nombre</label>
                    <x-adminlte-input name="name" type="name" value="{{ isset($entry)?$entry->name:'' }}" placeholder="Ej.: ABC Company"  required/>
                </div>

                <div class="form-group">
                    <label for="email">Correo</label>
                    <x-adminlte-input name="email" type="email" value="{{ isset($entry)?$entry->email:'' }}" placeholder="Ej.: jsmith@company.com" required/>
                </div>

                <x-adminlte-input-file name="logo" label="Logo (100 x 100)" placeholder="Choose a file..."/>

                <div class="form-group">
                    <label for="email">Pagina Web</label>
                    <x-adminlte-input name="website" type="text" value="{{ isset($entry)?$entry->website:'' }}" placeholder="Ej.: https://www.company.com" />
                </div>
            </div>

        </div>

        <button type="submit" class="btn btn-success"> <i class="fa fa-save mr-1"></i> {{$data['btn_action']}}</button>

    </form>

    @if(isset($entry))

    <hr>

    <h3>Lista de Empleados</h3>

    <div class="row mb-3">
        <div class="col-md-4">
            <a href="{{ url("admin/employees/create")}}" class="btn btn-primary form-inline">
                <i class="fa fa-plus mr-1"></i> Adicionar Empleado
            </a>
        </div>
    </div>

    <livewire:company-employees-table :company_id="$entry->id"/>

    @endif


@stop

@section('css')
    <link  href="{{ asset("vendor/sweetalert2/sweetalert2.min.css") }}" rel="stylesheet" />
@stop

@section('js')

    <script src="//unpkg.com/alpinejs" defer></script>
    <script src="{{ asset("vendor/sweetalert2/sweetalert2.min.js") }}"></script>

<script>

    window.addEventListener('SwalConfirm', function(event){
        swal.fire({
            title:event.detail.title,
            imageWidth:48,
            imageHeight:48,
            html:event.detail.html,
            showCloseButton:true,
            showCancelButton:true,
            cancelButtonText:'Cancelar',
            confirmButtonText:'Sí, Eliminar',
            cancelButtonColor:'#d33',
            confirmButtonColor:'#3085d6',
            width:450,
            allowOutsideClick:false
        }).then(function(result){
            if(result.value){
                window.livewire.emit('deleteEmploye',event.detail.id);
            }
        })
    })

    window.addEventListener('deleted', function(event){
        //window.livewire.emit('refreshList',event.detail.id);
        location.reload();
    });

</script>


@stop

resources/views/admin/company/list.blade.php
@extends('adminlte::page')

@section('title', 'Compañías')

@section('content_header')
    <h1>Compañías</h1>
@stop

@section('content')

    <p>Lista de Compañias</p>

    <div class="row mb-3">
        <div class="col-md-4">
            <a href="{{ url("admin/companies/create")}}" class="btn btn-primary form-inline">
                <i class="fa fa-plus mr-1"></i> Adicionar Compañia
            </a>
        </div>
    </div>

    <livewire:company-table/>

@stop

@section('css')
    <link  href="{{ asset("vendor/sweetalert2/sweetalert2.min.css") }}" rel="stylesheet" />
@stop

@section('js')
    <script src="//unpkg.com/alpinejs" defer></script>
    <script src="{{ asset("vendor/sweetalert2/sweetalert2.min.js") }}"></script>
    <script>

        window.addEventListener('SwalConfirm', function(event){
            swal.fire({
                title:event.detail.title,
                imageWidth:48,
                imageHeight:48,
                html:event.detail.html,
                showCloseButton:true,
                showCancelButton:true,
                cancelButtonText:'Cancelar',
                confirmButtonText:'Sí, Eliminar',
                cancelButtonColor:'#d33',
                confirmButtonColor:'#3085d6',
                width:450,
                allowOutsideClick:false
            }).then(function(result){
                if(result.value){
                    window.livewire.emit('deleteCompany',event.detail.id);
                }
            })
        })

        window.addEventListener('deletedCompany', function(event){
            //window.livewire.emit('refreshList',event.detail.id);
            location.reload();

        });

    </script>
@stop

resources/views/admin/company/show.blade.php
@extends('adminlte::page')

@section('title', 'Compañías')

@section('content_header')
    <h1>Companía <span class="text-blue">'{{$entry->name}}'</span></h1>
@stop

@section('content')

    <div class="row mb-3">
        <div class="col-md-4">
            <a href="{{ url("admin/companies/$entry->id/edit")}}" class="btn btn-primary form-inline">
                <i class="fas fa-fw fa-edit mr-1"></i> Editar Compañia
            </a>
        </div>
    </div>


    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Detalle</h3>
        </div>
        <form>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <img id="logo" src="{{ Storage::url($entry->logo) }}"
                                 class="product-image w-25 mb-2 img-thumbnail"
                                 alt="Logo {{$entry->name}}">
                        </div>
                    </div>

                </div>
                <div class="row">

                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Nombre</label>
                            <span class="form-control" >{{$entry->name}}</span>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Email</label>
                            <span class="form-control" >{{$entry->email}}</span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Pagina web</label>
                            <span class="form-control" >{{$entry->website}}</span>
                        </div>
                    </div>
                </div>


            </div>
            <div class="card-footer">

            </div>
        </form>
    </div>

    <hr>

    <h3>Lista de Empleados</h3>

    <livewire:company-employees-table :company_id="$entry->id"/>

@stop

@section('css')

@stop

@section('js')
    <script src="//unpkg.com/alpinejs" defer></script>
@stop