routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes(['register' => false]);

Route::middleware("auth")
    ->prefix("admin")
    ->as("admin.")
    ->group( function () {

        Route::get("/",  [App\Http\Controllers\Admin\IndexController::class,'index'])->name("index");

        Route::resource('companies', \App\Http\Controllers\Admin\CompanyController::class);
        Route::resource('employees', \App\Http\Controllers\Admin\EmployeeController::class);

    });

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Employee extends Model
{
    use HasFactory;

    protected $table = "employees";

    protected $fillable = [
        'company_id', 'first_name','last_name', 'email','phone'
    ];

    public function company():BelongsTo{
        return $this->belongsTo(Company::class);
    }


}

app/Http/Controllers/Admin/EmployeeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreEmployeeRequest;
use App\Http\Requests\UpdateEmployeeRequest;
use App\Models\Company;
use App\Models\Employee;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view("admin.employee.list");
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $data['accion'] = "create";
        $data['title']  = "Crear Empleado";
        $data['btn_action'] = "Guardar";

        $companies = Company::all();


        return view("admin.employee.form",compact('data','companies'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreEmployeeRequest $request)
    {
        //

        $form = $request->validated();

        $employee = Employee::create($form);

        return redirect("admin/companies/$employee->company_id/edit");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $entry = Employee::findOrFail($id);

        $companies = Company::all();

        $data['accion'] = "edit";
        $data['title']  = "Editar Empleado";
        $data['btn_action'] = "Actualizar";


        return view("admin.employee.form", compact('entry','data','companies'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateEmployeeRequest $request, $id)
    {

        $employee = Employee::findOrFail($id);

        $form = $request->validated();

        $employee->update($form);

        //dd($employee);

        return redirect("admin/companies/$employee->company_id/edit");

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //

        $employee = Employee::findOrFail($id);
        $employee->delete();

        return redirect("admin/companies/$employee->company_id/edit");
    }
}

app/Http/Livewire/Employee/BtnDelete.php
<?php

namespace App\Http\Livewire\Employee;

use App\Models\Employee;
use Livewire\Component;

class BtnDelete extends Component
{
    public $employee_id;
    public $employee;

    protected $listeners =[
        'deleteEmploye'
    ];

    public function mount($employee){
        $this->employee = $employee;
        $this->employee_id = $employee->id;
    }

    public function deleteConfirm($employee_id){

        $full_name =$this->employee->first_name." ".$this->employee->last_name;

        $this->dispatchBrowserEvent('SwalConfirm',[
            'title' => 'Eliminar Empleado',
            'html'  => "¿Desea eliminar al empleado <strong>$full_name ?</strong>",
            'id'    => $employee_id
        ]);


    }

    public function deleteEmploye($id){

        $delete = Employee::find($id)->delete();
        if($delete){
            $this->dispatchBrowserEvent('deleted');
        }

    }

    public function render()
    {
        return view('livewire.employee.btn-delete');
    }

}

app/Http/Livewire/EmployeeTable.php
<?php

namespace App\Http\Livewire;

use Carbon\Carbon;
use Rappasoft\LaravelLivewireTables\DataTableComponent;
use Rappasoft\LaravelLivewireTables\Views\Column;
use App\Models\Employee;

class EmployeeTable extends DataTableComponent
{
    protected $model = Employee::class;

    public function configure(): void
    {
        $this->setPrimaryKey('id');
    }

    public function columns(): array
    {
        return [
            Column::make("Id", "id")
                ->sortable(),
            Column::make(__("Compañia"), "company.name")
                ->sortable(),
            Column::make(__("Nombre"), "first_name")
                ->sortable()
                ->searchable(),
            Column::make(__("Apellido"), "last_name")
                ->sortable()
                ->searchable(),
            Column::make(__("Email"), "email")
                ->sortable()
                ->searchable(),
            Column::make(__("Telefono"), "phone")
                ->sortable()
                ->searchable(),
            Column::make(__("Fecha creacion"), "created_at")
                ->sortable()
                ->format(
                    fn($value, $row, Column $column) => Carbon::create($row->created_at)->format("d/m/Y H:i")
                ),
            Column::make(__("Fecha actualización"), "updated_at")
                ->sortable()
                ->format(
                    fn($value, $row, Column $column) => Carbon::create($row->updated_at)->format("d/m/Y H:i")
                ),
            Column::make('Actions','id')
                ->view('admin.employee.actions')
                ->html()->excludeFromColumnSelect(),
        ];
    }
}

resources/views/admin/employee/actions.blade.php
<div class="btn-group" role="group" aria-label="Acciones">

    <a href="{{ route("admin.employees.edit",$row) }}" class="btn btn-sm btn-primary">
        <i class="fas fa-fw fa-edit"></i>
    </a>

    @livewire("employee.btn-delete",['employee' => $row])

</div>

resources/views/admin/employee/form.blade.php
@extends('adminlte::page')

@section('title',$data['title'])

@section('content_header')
    <h1>{{$data['title']}}</h1>
@stop

@section('content')

@if(isset($entry))
    <form method="POST"  action="{{ url("admin/employees/".$entry->id) }}" enctype="multipart/form-data" >
    @method('PUT')
@else
    <form method="POST" action="{{ url("admin/employees") }}" enctype="multipart/form-data" >
        @endif

        @csrf

        <input type="hidden" id="id" name="id" value="{{ isset($entry)?$entry->id:0 }}" />

        <div class="card card-success">
            <div class="card-header">
                <h3 class="card-title">Detalle</h3>
            </div>
            <div class="card-body">

                <div class="form-group">
                    <label for="name">Compañia</label>
                    <select class="form-control" name="company_id" id="company_id">
                        @foreach($companies as $line)
                            <option value="{{$line->id}}" @if(isset($entry) and $entry->company_id == $line->id) selected="selected" @endif >{{$line->name}}</option>
                        @endforeach
                    </select>
                </div>

                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <x-adminlte-input label="Nombre" name="first_name" type="text" value="{{ isset($entry)?$entry->first_name:'' }}" placeholder="Ej.: John"  required/>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <x-adminlte-input label="Apellido" name="last_name" type="text" value="{{ isset($entry)?$entry->last_name:'' }}" placeholder="Ej.: Smith" required/>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <x-adminlte-input label="Correo" name="email" type="email" value="{{ isset($entry)?$entry->email:'' }}" placeholder="Ej.: jsmith@company.com"  required/>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <x-adminlte-input label="Telefono" name="phone" type="text" value="{{ isset($entry)?$entry->phone:'' }}" placeholder="" />
                        </div>
                    </div>
                </div>

            </div>

        </div>

        <button type="submit" class="btn btn-success"> <i class="fa fa-save mr-1"></i> {{$data['btn_action']}}</button>

    </form>



@stop

@section('css')

@stop

@section('js')

    <script src="//unpkg.com/alpinejs" defer></script>
    <script type="text/javascript">

    </script>

@stop

resources/views/admin/employee/list.blade.php
@extends('adminlte::page')

@section('title', 'Empleados')

@section('content_header')
    <h1>Empleados</h1>
@stop

@section('content')

    <p>Lista de Empleados</p>

    <livewire:employee-table/>

@stop

@section('css')

@stop

@section('js')
    <script src="//unpkg.com/alpinejs" defer></script>
    <script> console.log('Hi!'); </script>
@stop